# Generated by Django 5.0.11 on 2026-07-11 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jasmin', '0005_evalpyfilter_param_source'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', help_text='Shared id for messages submitted together in a bulk send', max_length=64)),
                ('batch_kind', models.CharField(choices=[('single', 'Single'), ('bulk', 'Bulk')], default='single', max_length=16)),
                ('to_addr', models.CharField(db_index=True, max_length=32)),
                ('from_addr', models.CharField(blank=True, default='', max_length=32)),
                ('content', models.TextField()),
                ('coding', models.PositiveSmallIntegerField(default=0)),
                ('dlr_level', models.PositiveSmallIntegerField(default=2, help_text='1=SMSC only, 2=terminal only, 3=both (Jasmin dlr-level)')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('acked', 'Acknowledged'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], db_index=True, default='queued', max_length=16)),
                ('jasmin_msg_id', models.CharField(blank=True, db_index=True, default='', help_text='Message id returned by Jasmin /send', max_length=64)),
                ('submit_response', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('dlr_status', models.CharField(blank=True, default='', max_length=64)),
                ('dlr_raw', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_dlr_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creations', to=settings.AUTH_USER_MODEL)),
                ('jasmin_user', models.ForeignKey(blank=True, help_text='Jasmin HTTP API user used to submit this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='jasmin.jasminuser')),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='workspace.workspace')),
            ],
            options={
                'db_table': 'messaging_outbound_message',
                'ordering': ('-created_on',),
                'indexes': [models.Index(fields=['workspace', 'status'], name='messaging_o_workspa_78ef7a_idx'), models.Index(fields=['workspace', '-created_on'], name='messaging_o_workspa_0029f7_idx')],
            },
        ),
    ]
