# Generated by Django 5.0.11 on 2026-07-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundmessage',
            name='dlr_level',
            field=models.PositiveSmallIntegerField(default=3, help_text='1=SMSC only, 2=terminal only, 3=both (Jasmin dlr-level)'),
        ),
    ]
