# Generated by Django 5.0.11 on 2026-07-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_client_message_ids'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboundmessage',
            new_name='messaging_o_workspa_8c7ca6_idx',
            old_name='msg_ws_client_msgid_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundmessage',
            new_name='messaging_o_workspa_f96eab_idx',
            old_name='msg_ws_client_batch_idx',
        ),
    ]
