# Generated by Django 5.0.11 on 2026-07-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='jasmin_user_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When Jasmin user credentials were last synced into Django for this workspace.', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_user_sync_interval_mins',
            field=models.PositiveIntegerField(default=5, help_text='How often (minutes) to pull live Jasmin user credentials/quotas into Django. Set to 0 to disable automatic sync for this workspace.'),
        ),
    ]
