# Generated by Django 5.0.11 on 2026-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_jasmin_user_sync_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='jasmin_connection_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_http_api_url',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_link',
            field=models.CharField(blank=True, choices=[('', 'Not configured'), ('demo', 'Local demo Jasmin'), ('custom', 'My own Jasmin')], default='', help_text='How this workspace reaches Jasmin when JOYCE_JASMIN_MODE=multi.', max_length=16),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_router_pb_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_router_pb_password',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_router_pb_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_router_pb_username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_smpp_pb_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_smpp_pb_password',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_smpp_pb_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='jasmin_smpp_pb_username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
