# Generated by Django 5.0.11 on 2026-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_jasmin_connection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='jasmin_config_last_imported_at',
            field=models.DateTimeField(blank=True, help_text='When full Jasmin config (groups/users/connectors/routes/…) was last pulled into Django.', null=True),
        ),
    ]
