# Generated by Django 5.0.11

from django.db import migrations, models


def forwards(apps, schema_editor):
    """Existing workspaces that never chose a link were on implicit local/demo Jasmin."""
    WorkSpace = apps.get_model("workspace", "WorkSpace")
    WorkSpace.objects.filter(jasmin_link="").update(jasmin_link="demo")


def backwards(apps, schema_editor):
    WorkSpace = apps.get_model("workspace", "WorkSpace")
    WorkSpace.objects.filter(jasmin_link="demo").update(jasmin_link="")


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0004_route_order_unique_and_config_import"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="workspace",
            name="jasmin_link",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not configured"),
                    ("demo", "Local demo Jasmin"),
                    ("custom", "My own Jasmin"),
                ],
                default="",
                help_text="How this workspace reaches Jasmin: demo gateway or your own.",
                max_length=16,
            ),
        ),
    ]
