# Generated by Django 5.0.11 on 2026-07-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_messaging_api_and_external_dlr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='jasmin_rest_api_url',
            field=models.URLField(blank=True, default='', help_text='Optional Jasmin REST API base URL (sendbatch). Without REST, Jasmin uses the native HTTP API; leave empty to keep Joyce bulk on async HTTP /send.', max_length=512),
        ),
    ]
