# Generated by Django 5.0.7 on 2024-07-20 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JasminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('gid', models.CharField(db_index=True, help_text='This matches the group id created in Jasmin', max_length=255, unique=True, verbose_name='Group Id')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jasmin_group',
            },
        ),
        migrations.CreateModel(
            name='JasminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('username', models.CharField(help_text='This matches the user username created in Jasmin', max_length=255, unique=True, verbose_name='Username')),
                ('password', models.CharField(help_text='We shall store this password in clear text here', max_length=255, verbose_name='Password')),
                ('enabled', models.BooleanField(default=True)),
                ('mt_credential', models.JSONField(blank=True, default=dict)),
                ('smpps_credential', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.jasmingroup')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jasmin_user',
            },
        ),
    ]
