# Generated by Django 5.0.11 on 2025-04-26 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JasminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('gid', models.CharField(db_index=True, help_text="This matches the group id created in Jasmin and will be prefixed with Workspace's prefix", max_length=30, unique=True, verbose_name='Group Id')),
                ('description', models.TextField(blank=True, help_text='Short description about purpose of this group.', null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'jasmin_group',
            },
        ),
        migrations.CreateModel(
            name='JasminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('username', models.CharField(help_text='This matches the user username created in Jasmin', max_length=255, unique=True, verbose_name='Username')),
                ('password', models.CharField(help_text='We shall store this password in clear text here', max_length=255, verbose_name='Password')),
                ('enabled', models.BooleanField(default=True)),
                ('mt_credential', models.JSONField(blank=True, default=dict)),
                ('smpps_credential', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'jasmin_user',
            },
        ),
    ]
