# Generated by Django 5.0.11 on 2025-05-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasminhttpconnector',
            name='cid',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jasminhttpconnector',
            name='connector_type',
            field=models.CharField(choices=[('SMPP', 'SMPP'), ('HTTP', 'HTTP')], default='HTTP', max_length=4),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='cid',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='connector_type',
            field=models.CharField(choices=[('SMPP', 'SMPP'), ('HTTP', 'HTTP')], default='HTTP', max_length=4),
        ),
    ]
