# Generated by Django 5.0.11 on 2026-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0002_interceptor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasmininterceptor',
            name='filters',
            field=models.ManyToManyField(blank=True, help_text='Required for StaticMO/StaticMTInterceptor. Ignored for DefaultInterceptor.', to='jasmin.jasminfilter'),
        ),
    ]
