# Generated by Django 5.0.11 on 2025-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0002_alter_jasminhttpconnector_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasminhttpconnector',
            name='cid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='cid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
