# Generated by Django 5.0.11 on 2025-05-03 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0002_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JasminMtRouter',
            new_name='JasminMtRoute',
        ),
        migrations.AlterModelTable(
            name='jasminmtroute',
            table='jasmin_mt_route',
        ),
    ]
