# Generated by Django 5.0.11 on 2025-04-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasmingroup',
            name='gid',
            field=models.CharField(db_index=True, help_text="This matches the group id created in Jasmin and will be prefixed with Workspace's prefix", max_length=16, unique=True, verbose_name='Group Id'),
        ),
    ]
