# Generated by Django 5.0.11 on 2025-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0003_alter_jasminroute_connectors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasminroute',
            name='router_type',
            field=models.CharField(choices=[('DefaultRoute', 'Default route'), ('StaticMTRoute', 'Static MTRoute'), ('RandomRoundrobinMTRoute', 'Random Roundrobin MTRoute'), ('FailoverMTRoute', 'Failover MTRoute'), ('StaticMORoute', 'Static MORoute'), ('RandomRoundrobinMORoute', 'Random Roundrobin MORoute'), ('FailoverMORoute', 'Failover MORoute')], default='DefaultRoute', help_text='Type of router for message routing.', max_length=25),
        ),
    ]
