# Generated by Django 5.0.11 on 2025-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0003_alter_jasminhttpconnector_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasminhttpconnector',
            name='base_url',
            field=models.URLField(help_text='A valid URL e.g https://example.tech or http://192.168.1.10:8000/sms', max_length=255),
        ),
    ]
