# Generated by Django 5.0.11 on 2025-04-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0003_alter_jasminsmppconnector_address_npi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='address_npi',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'ISDN'), (2, 'Data'), (3, 'Telex'), (4, 'Land Mobile'), (5, 'National'), (6, 'Private'), (10, 'Ermes'), (14, 'Internet'), (18, 'WAP Client ID')], default=1, help_text='Bind address NPI'),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='address_ton',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'International'), (2, 'National'), (3, 'Network Specific'), (4, 'Subscriber Number'), (5, 'Alphanumeric'), (6, 'Abbreviated')], default=0, help_text='Bind address TON'),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='dest_addr_npi',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'ISDN'), (2, 'Data'), (3, 'Telex'), (4, 'Land Mobile'), (5, 'National'), (6, 'Private'), (10, 'Ermes'), (14, 'Internet'), (18, 'WAP Client ID')], default=1, help_text='Destination address NPI'),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='dest_addr_ton',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'International'), (2, 'National'), (3, 'Network Specific'), (4, 'Subscriber Number'), (5, 'Alphanumeric'), (6, 'Abbreviated')], default=1, help_text='Destination address TON'),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='priority_flag',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, help_text='SMS-MT default priority'),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='registered_delivery',
            field=models.BooleanField(default=False, help_text='Request SMSC delivery receipt'),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='replace_if_present_flag',
            field=models.IntegerField(choices=[(0, 'Do not replace'), (1, 'Replace')], default=0, help_text='Replace if present flag'),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='source_addr_npi',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'ISDN'), (2, 'Data'), (3, 'Telex'), (4, 'Land Mobile'), (5, 'National'), (6, 'Private'), (10, 'Ermes'), (14, 'Internet'), (18, 'WAP Client ID')], default=1, help_text='Source address NPI'),
        ),
        migrations.AlterField(
            model_name='jasminsmppconnector',
            name='source_addr_ton',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'International'), (2, 'National'), (3, 'Network Specific'), (4, 'Subscriber Number'), (5, 'Alphanumeric'), (6, 'Abbreviated')], default=2, help_text='Source address TON'),
        ),
    ]
