# Generated by Django 5.0.11 on 2025-05-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0004_alter_jasminhttpconnector_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasminhttpconnector',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=4),
        ),
    ]
