# Generated by Django 5.0.11 on 2025-05-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0005_alter_jasminhttpconnector_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasminhttpconnector',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the purpose of this connector', null=True),
        ),
    ]
