# Generated by Django 5.0.11 on 2026-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin', '0005_evalpyfilter_param_source'),
        ('workspace', '0004_route_order_unique_and_config_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasminroute',
            name='order',
            field=models.IntegerField(help_text='Route order within this workspace and nature (MO/MT).'),
        ),
        migrations.AlterUniqueTogether(
            name='jasminroute',
            unique_together={('workspace', 'nature', 'order')},
        ),
    ]
